"""create check tables

Revision ID: 0e08dc5a923b
Revises: de4793c8072f
Create Date: 2026-04-21 19:13:01.513328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e08dc5a923b'
down_revision: Union[str, Sequence[str], None] = 'de4793c8072f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issued_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('check_number', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.Enum('TRY', 'USD', 'EUR', 'GBP', name='issued_check_currency_code', native_enum=False, length=10), server_default='TRY', nullable=False),
    sa.Column('status', sa.Enum('PREPARED', 'GIVEN', 'PAID', 'CANCELLED', 'RISK', name='issued_check_status', native_enum=False, length=20), server_default='PREPARED', nullable=False),
    sa.Column('paid_transaction_id', sa.Integer(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paid_transaction_id'], ['bank_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['business_partners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_id', 'check_number', name='uq_issued_checks_bank_account_id_check_number')
    )
    op.create_index(op.f('ix_issued_checks_bank_account_id'), 'issued_checks', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_issued_checks_cancelled_by_user_id'), 'issued_checks', ['cancelled_by_user_id'], unique=False)
    op.create_index(op.f('ix_issued_checks_check_number'), 'issued_checks', ['check_number'], unique=False)
    op.create_index(op.f('ix_issued_checks_created_by_user_id'), 'issued_checks', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_issued_checks_due_date'), 'issued_checks', ['due_date'], unique=False)
    op.create_index(op.f('ix_issued_checks_issue_date'), 'issued_checks', ['issue_date'], unique=False)
    op.create_index(op.f('ix_issued_checks_paid_transaction_id'), 'issued_checks', ['paid_transaction_id'], unique=True)
    op.create_index(op.f('ix_issued_checks_reference_no'), 'issued_checks', ['reference_no'], unique=False)
    op.create_index(op.f('ix_issued_checks_status'), 'issued_checks', ['status'], unique=False)
    op.create_index(op.f('ix_issued_checks_supplier_id'), 'issued_checks', ['supplier_id'], unique=False)
    op.create_table('received_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('collection_bank_account_id', sa.Integer(), nullable=True),
    sa.Column('drawer_bank_name', sa.String(length=150), nullable=False),
    sa.Column('drawer_branch_name', sa.String(length=150), nullable=True),
    sa.Column('check_number', sa.String(length=100), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.Enum('TRY', 'USD', 'EUR', 'GBP', name='received_check_currency_code', native_enum=False, length=10), server_default='TRY', nullable=False),
    sa.Column('status', sa.Enum('PORTFOLIO', 'GIVEN_TO_BANK', 'IN_COLLECTION', 'COLLECTED', 'BOUNCED', 'RETURNED', 'ENDORSED', 'CANCELLED', name='received_check_status', native_enum=False, length=20), server_default='PORTFOLIO', nullable=False),
    sa.Column('collected_transaction_id', sa.Integer(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collected_transaction_id'], ['bank_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_bank_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['business_partners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drawer_bank_name', 'check_number', name='uq_received_checks_drawer_bank_name_check_number')
    )
    op.create_index(op.f('ix_received_checks_cancelled_by_user_id'), 'received_checks', ['cancelled_by_user_id'], unique=False)
    op.create_index(op.f('ix_received_checks_check_number'), 'received_checks', ['check_number'], unique=False)
    op.create_index(op.f('ix_received_checks_collected_transaction_id'), 'received_checks', ['collected_transaction_id'], unique=True)
    op.create_index(op.f('ix_received_checks_collection_bank_account_id'), 'received_checks', ['collection_bank_account_id'], unique=False)
    op.create_index(op.f('ix_received_checks_created_by_user_id'), 'received_checks', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_received_checks_customer_id'), 'received_checks', ['customer_id'], unique=False)
    op.create_index(op.f('ix_received_checks_drawer_bank_name'), 'received_checks', ['drawer_bank_name'], unique=False)
    op.create_index(op.f('ix_received_checks_due_date'), 'received_checks', ['due_date'], unique=False)
    op.create_index(op.f('ix_received_checks_received_date'), 'received_checks', ['received_date'], unique=False)
    op.create_index(op.f('ix_received_checks_reference_no'), 'received_checks', ['reference_no'], unique=False)
    op.create_index(op.f('ix_received_checks_status'), 'received_checks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_received_checks_status'), table_name='received_checks')
    op.drop_index(op.f('ix_received_checks_reference_no'), table_name='received_checks')
    op.drop_index(op.f('ix_received_checks_received_date'), table_name='received_checks')
    op.drop_index(op.f('ix_received_checks_due_date'), table_name='received_checks')
    op.drop_index(op.f('ix_received_checks_drawer_bank_name'), table_name='received_checks')
    op.drop_index(op.f('ix_received_checks_customer_id'), table_name='received_checks')
    op.drop_index(op.f('ix_received_checks_created_by_user_id'), table_name='received_checks')
    op.drop_index(op.f('ix_received_checks_collection_bank_account_id'), table_name='received_checks')
    op.drop_index(op.f('ix_received_checks_collected_transaction_id'), table_name='received_checks')
    op.drop_index(op.f('ix_received_checks_check_number'), table_name='received_checks')
    op.drop_index(op.f('ix_received_checks_cancelled_by_user_id'), table_name='received_checks')
    op.drop_table('received_checks')
    op.drop_index(op.f('ix_issued_checks_supplier_id'), table_name='issued_checks')
    op.drop_index(op.f('ix_issued_checks_status'), table_name='issued_checks')
    op.drop_index(op.f('ix_issued_checks_reference_no'), table_name='issued_checks')
    op.drop_index(op.f('ix_issued_checks_paid_transaction_id'), table_name='issued_checks')
    op.drop_index(op.f('ix_issued_checks_issue_date'), table_name='issued_checks')
    op.drop_index(op.f('ix_issued_checks_due_date'), table_name='issued_checks')
    op.drop_index(op.f('ix_issued_checks_created_by_user_id'), table_name='issued_checks')
    op.drop_index(op.f('ix_issued_checks_check_number'), table_name='issued_checks')
    op.drop_index(op.f('ix_issued_checks_cancelled_by_user_id'), table_name='issued_checks')
    op.drop_index(op.f('ix_issued_checks_bank_account_id'), table_name='issued_checks')
    op.drop_table('issued_checks')
    # ### end Alembic commands ###
