"""create bank transactions

Revision ID: 13f2a75d0105
Revises: ad975dc229d4
Create Date: 2026-04-21 18:42:55.866348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f2a75d0105'
down_revision: Union[str, Sequence[str], None] = 'ad975dc229d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='transaction_direction', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'REALIZED', 'CANCELLED', name='bank_transaction_status', native_enum=False, length=20), server_default='REALIZED', nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.Enum('TRY', 'USD', 'EUR', 'GBP', name='bank_transaction_currency_code', native_enum=False, length=10), server_default='TRY', nullable=False),
    sa.Column('source_type', sa.Enum('OPENING_BALANCE', 'CASH_DEPOSIT', 'BANK_TRANSFER', 'ISSUED_CHECK', 'RECEIVED_CHECK', 'POS_SETTLEMENT', 'MANUAL_ADJUSTMENT', 'OTHER', name='financial_source_type', native_enum=False, length=40), server_default='OTHER', nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_bank_account_id'), 'bank_transactions', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_cancelled_by_user_id'), 'bank_transactions', ['cancelled_by_user_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_created_by_user_id'), 'bank_transactions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_reference_no'), 'bank_transactions', ['reference_no'], unique=False)
    op.create_index(op.f('ix_bank_transactions_source_id'), 'bank_transactions', ['source_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_source_type'), 'bank_transactions', ['source_type'], unique=False)
    op.create_index(op.f('ix_bank_transactions_status'), 'bank_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_date'), 'bank_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_value_date'), 'bank_transactions', ['value_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transactions_value_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_transaction_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_status'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_source_type'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_source_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_reference_no'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_created_by_user_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_cancelled_by_user_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    # ### end Alembic commands ###
