"""add bsiv fields to received check discount batches

Revision ID: 27f12c94ab4b
Revises: 7209ee77c414
Create Date: 2026-04-24 16:27:04.489684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f12c94ab4b'
down_revision: Union[str, Sequence[str], None] = '7209ee77c414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('received_check_discount_batch_items', sa.Column('bsiv_rate', sa.Numeric(precision=18, scale=6), server_default='0.300000', nullable=False))
    op.add_column('received_check_discount_batch_items', sa.Column('bsiv_amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False))
    op.add_column('received_check_discount_batches', sa.Column('bsiv_rate', sa.Numeric(precision=18, scale=6), server_default='0.300000', nullable=False))
    op.add_column('received_check_discount_batches', sa.Column('total_bsiv_amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('received_check_discount_batches', 'total_bsiv_amount')
    op.drop_column('received_check_discount_batches', 'bsiv_rate')
    op.drop_column('received_check_discount_batch_items', 'bsiv_amount')
    op.drop_column('received_check_discount_batch_items', 'bsiv_rate')
    # ### end Alembic commands ###
