"""create bank transfers

Revision ID: 4ce1c87fd363
Revises: 13f2a75d0105
Create Date: 2026-04-21 19:01:38.388425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce1c87fd363'
down_revision: Union[str, Sequence[str], None] = '13f2a75d0105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_bank_account_id', sa.Integer(), nullable=False),
    sa.Column('to_bank_account_id', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.Enum('TRY', 'USD', 'EUR', 'GBP', name='bank_transfer_currency_code', native_enum=False, length=10), server_default='TRY', nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'REALIZED', 'CANCELLED', name='bank_transfer_status', native_enum=False, length=20), server_default='REALIZED', nullable=False),
    sa.Column('outgoing_transaction_id', sa.Integer(), nullable=True),
    sa.Column('incoming_transaction_id', sa.Integer(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_bank_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incoming_transaction_id'], ['bank_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outgoing_transaction_id'], ['bank_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_bank_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transfers_cancelled_by_user_id'), 'bank_transfers', ['cancelled_by_user_id'], unique=False)
    op.create_index(op.f('ix_bank_transfers_created_by_user_id'), 'bank_transfers', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_bank_transfers_from_bank_account_id'), 'bank_transfers', ['from_bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_transfers_incoming_transaction_id'), 'bank_transfers', ['incoming_transaction_id'], unique=True)
    op.create_index(op.f('ix_bank_transfers_outgoing_transaction_id'), 'bank_transfers', ['outgoing_transaction_id'], unique=True)
    op.create_index(op.f('ix_bank_transfers_reference_no'), 'bank_transfers', ['reference_no'], unique=False)
    op.create_index(op.f('ix_bank_transfers_status'), 'bank_transfers', ['status'], unique=False)
    op.create_index(op.f('ix_bank_transfers_to_bank_account_id'), 'bank_transfers', ['to_bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_transfers_transfer_date'), 'bank_transfers', ['transfer_date'], unique=False)
    op.create_index(op.f('ix_bank_transfers_value_date'), 'bank_transfers', ['value_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transfers_value_date'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_transfer_date'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_to_bank_account_id'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_status'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_reference_no'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_outgoing_transaction_id'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_incoming_transaction_id'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_from_bank_account_id'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_created_by_user_id'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_cancelled_by_user_id'), table_name='bank_transfers')
    op.drop_table('bank_transfers')
    # ### end Alembic commands ###
