"""create pos tables

Revision ID: 6d03faae2882
Revises: 0e08dc5a923b
Create Date: 2026-04-22 10:37:15.556997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d03faae2882'
down_revision: Union[str, Sequence[str], None] = '0e08dc5a923b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('terminal_no', sa.String(length=100), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=18, scale=6), server_default='0.000000', nullable=False),
    sa.Column('settlement_delay_days', sa.Integer(), server_default='1', nullable=False),
    sa.Column('currency_code', sa.Enum('TRY', 'USD', 'EUR', 'GBP', name='pos_device_currency_code', native_enum=False, length=10), server_default='TRY', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_id', 'terminal_no', name='uq_pos_devices_bank_account_id_terminal_no')
    )
    op.create_index(op.f('ix_pos_devices_bank_account_id'), 'pos_devices', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_pos_devices_name'), 'pos_devices', ['name'], unique=False)
    op.create_index(op.f('ix_pos_devices_terminal_no'), 'pos_devices', ['terminal_no'], unique=False)
    op.create_table('pos_settlements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pos_device_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('expected_settlement_date', sa.Date(), nullable=False),
    sa.Column('realized_settlement_date', sa.Date(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=18, scale=6), server_default='0.000000', nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.Enum('TRY', 'USD', 'EUR', 'GBP', name='pos_settlement_currency_code', native_enum=False, length=10), server_default='TRY', nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'REALIZED', 'CANCELLED', 'MISMATCH', name='pos_settlement_status', native_enum=False, length=20), server_default='PLANNED', nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pos_device_id'], ['pos_devices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_settlements_bank_transaction_id'), 'pos_settlements', ['bank_transaction_id'], unique=True)
    op.create_index(op.f('ix_pos_settlements_cancelled_by_user_id'), 'pos_settlements', ['cancelled_by_user_id'], unique=False)
    op.create_index(op.f('ix_pos_settlements_created_by_user_id'), 'pos_settlements', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_pos_settlements_expected_settlement_date'), 'pos_settlements', ['expected_settlement_date'], unique=False)
    op.create_index(op.f('ix_pos_settlements_pos_device_id'), 'pos_settlements', ['pos_device_id'], unique=False)
    op.create_index(op.f('ix_pos_settlements_realized_settlement_date'), 'pos_settlements', ['realized_settlement_date'], unique=False)
    op.create_index(op.f('ix_pos_settlements_reference_no'), 'pos_settlements', ['reference_no'], unique=False)
    op.create_index(op.f('ix_pos_settlements_status'), 'pos_settlements', ['status'], unique=False)
    op.create_index(op.f('ix_pos_settlements_transaction_date'), 'pos_settlements', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pos_settlements_transaction_date'), table_name='pos_settlements')
    op.drop_index(op.f('ix_pos_settlements_status'), table_name='pos_settlements')
    op.drop_index(op.f('ix_pos_settlements_reference_no'), table_name='pos_settlements')
    op.drop_index(op.f('ix_pos_settlements_realized_settlement_date'), table_name='pos_settlements')
    op.drop_index(op.f('ix_pos_settlements_pos_device_id'), table_name='pos_settlements')
    op.drop_index(op.f('ix_pos_settlements_expected_settlement_date'), table_name='pos_settlements')
    op.drop_index(op.f('ix_pos_settlements_created_by_user_id'), table_name='pos_settlements')
    op.drop_index(op.f('ix_pos_settlements_cancelled_by_user_id'), table_name='pos_settlements')
    op.drop_index(op.f('ix_pos_settlements_bank_transaction_id'), table_name='pos_settlements')
    op.drop_table('pos_settlements')
    op.drop_index(op.f('ix_pos_devices_terminal_no'), table_name='pos_devices')
    op.drop_index(op.f('ix_pos_devices_name'), table_name='pos_devices')
    op.drop_index(op.f('ix_pos_devices_bank_account_id'), table_name='pos_devices')
    op.drop_table('pos_devices')
    # ### end Alembic commands ###
