"""add received check discount batch tables

Revision ID: 7209ee77c414
Revises: 9a7d2368bb48
Create Date: 2026-04-24 14:34:37.250357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7209ee77c414'
down_revision: Union[str, Sequence[str], None] = '9a7d2368bb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('received_check_discount_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=True),
    sa.Column('discount_date', sa.Date(), nullable=False),
    sa.Column('annual_interest_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('day_basis', sa.Integer(), server_default='365', nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_interest_expense_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_commission_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_discount_expense_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_bank_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.Enum('TRY', 'USD', 'EUR', 'GBP', name='received_check_currency_code', native_enum=False, length=10), server_default='TRY', nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_received_check_discount_batches_bank_account_id'), 'received_check_discount_batches', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_received_check_discount_batches_bank_transaction_id'), 'received_check_discount_batches', ['bank_transaction_id'], unique=True)
    op.create_index(op.f('ix_received_check_discount_batches_created_by_user_id'), 'received_check_discount_batches', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_received_check_discount_batches_discount_date'), 'received_check_discount_batches', ['discount_date'], unique=False)
    op.create_index(op.f('ix_received_check_discount_batches_reference_no'), 'received_check_discount_batches', ['reference_no'], unique=False)
    op.create_table('received_check_discount_batch_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('received_check_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('days_to_due', sa.Integer(), nullable=False),
    sa.Column('annual_interest_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('day_basis', sa.Integer(), server_default='365', nullable=False),
    sa.Column('interest_expense_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_expense_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.Enum('TRY', 'USD', 'EUR', 'GBP', name='received_check_currency_code', native_enum=False, length=10), server_default='TRY', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['received_check_discount_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_check_id'], ['received_checks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('received_check_id', name='uq_received_check_discount_batch_items_received_check_id')
    )
    op.create_index(op.f('ix_received_check_discount_batch_items_batch_id'), 'received_check_discount_batch_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_received_check_discount_batch_items_due_date'), 'received_check_discount_batch_items', ['due_date'], unique=False)
    op.create_index(op.f('ix_received_check_discount_batch_items_received_check_id'), 'received_check_discount_batch_items', ['received_check_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_received_check_discount_batch_items_received_check_id'), table_name='received_check_discount_batch_items')
    op.drop_index(op.f('ix_received_check_discount_batch_items_due_date'), table_name='received_check_discount_batch_items')
    op.drop_index(op.f('ix_received_check_discount_batch_items_batch_id'), table_name='received_check_discount_batch_items')
    op.drop_table('received_check_discount_batch_items')
    op.drop_index(op.f('ix_received_check_discount_batches_reference_no'), table_name='received_check_discount_batches')
    op.drop_index(op.f('ix_received_check_discount_batches_discount_date'), table_name='received_check_discount_batches')
    op.drop_index(op.f('ix_received_check_discount_batches_created_by_user_id'), table_name='received_check_discount_batches')
    op.drop_index(op.f('ix_received_check_discount_batches_bank_transaction_id'), table_name='received_check_discount_batches')
    op.drop_index(op.f('ix_received_check_discount_batches_bank_account_id'), table_name='received_check_discount_batches')
    op.drop_table('received_check_discount_batches')
    # ### end Alembic commands ###
