"""add role permissions table

Revision ID: 9004abc69eda
Revises: 27f12c94ab4b
Create Date: 2026-04-28 08:05:52.231986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9004abc69eda'
down_revision: Union[str, Sequence[str], None] = '27f12c94ab4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FINANCE', 'DATA_ENTRY', 'VIEWER', name='role_permission_user_role', native_enum=False, length=30), nullable=False),
    sa.Column('permission', sa.String(length=120), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permission', name='uq_role_permissions_role_permission')
    )
    op.create_index('ix_role_permissions_permission', 'role_permissions', ['permission'], unique=False)
    op.create_index('ix_role_permissions_role', 'role_permissions', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_permissions_role', table_name='role_permissions')
    op.drop_index('ix_role_permissions_permission', table_name='role_permissions')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
