"""add received check movements table

Revision ID: 9a7d2368bb48
Revises: c3717073604a
Create Date: 2026-04-23 15:38:06.784511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7d2368bb48'
down_revision: Union[str, Sequence[str], None] = 'c3717073604a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('received_check_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('received_check_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('REGISTERED', 'SENT_TO_BANK_COLLECTION', 'MARKED_IN_COLLECTION', 'COLLECTED', 'ENDORSED', 'DISCOUNTED', 'BOUNCED', 'RETURNED', 'CANCELLED', 'REVERSED', name='received_check_movement_type', native_enum=False, length=40), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('from_status', sa.Enum('PORTFOLIO', 'GIVEN_TO_BANK', 'IN_COLLECTION', 'COLLECTED', 'BOUNCED', 'RETURNED', 'ENDORSED', 'DISCOUNTED', 'CANCELLED', name='received_check_status', native_enum=False, length=20), nullable=True),
    sa.Column('to_status', sa.Enum('PORTFOLIO', 'GIVEN_TO_BANK', 'IN_COLLECTION', 'COLLECTED', 'BOUNCED', 'RETURNED', 'ENDORSED', 'DISCOUNTED', 'CANCELLED', name='received_check_status', native_enum=False, length=20), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('counterparty_text', sa.String(length=200), nullable=True),
    sa.Column('purpose_text', sa.Text(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.Enum('TRY', 'USD', 'EUR', 'GBP', name='received_check_currency_code', native_enum=False, length=10), server_default='TRY', nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('discount_expense_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_bank_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['received_check_id'], ['received_checks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_received_check_movements_bank_account_id'), 'received_check_movements', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_received_check_movements_created_by_user_id'), 'received_check_movements', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_received_check_movements_movement_date'), 'received_check_movements', ['movement_date'], unique=False)
    op.create_index(op.f('ix_received_check_movements_movement_type'), 'received_check_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_received_check_movements_received_check_id'), 'received_check_movements', ['received_check_id'], unique=False)
    op.create_index(op.f('ix_received_check_movements_reference_no'), 'received_check_movements', ['reference_no'], unique=False)
    op.create_index(op.f('ix_received_check_movements_to_status'), 'received_check_movements', ['to_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_received_check_movements_to_status'), table_name='received_check_movements')
    op.drop_index(op.f('ix_received_check_movements_reference_no'), table_name='received_check_movements')
    op.drop_index(op.f('ix_received_check_movements_received_check_id'), table_name='received_check_movements')
    op.drop_index(op.f('ix_received_check_movements_movement_type'), table_name='received_check_movements')
    op.drop_index(op.f('ix_received_check_movements_movement_date'), table_name='received_check_movements')
    op.drop_index(op.f('ix_received_check_movements_created_by_user_id'), table_name='received_check_movements')
    op.drop_index(op.f('ix_received_check_movements_bank_account_id'), table_name='received_check_movements')
    op.drop_table('received_check_movements')
    # ### end Alembic commands ###
