"""add pos settlement difference fields

Revision ID: 9cfe2ef5ecf8
Revises: 6d03faae2882
Create Date: 2026-04-22 11:03:00.591989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfe2ef5ecf8'
down_revision: Union[str, Sequence[str], None] = '6d03faae2882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pos_settlements', sa.Column('actual_net_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('pos_settlements', sa.Column('difference_amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False))
    op.add_column('pos_settlements', sa.Column('difference_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pos_settlements', 'difference_reason')
    op.drop_column('pos_settlements', 'difference_amount')
    op.drop_column('pos_settlements', 'actual_net_amount')
    # ### end Alembic commands ###
