"""create business partners

Revision ID: de4793c8072f
Revises: 4ce1c87fd363
Create Date: 2026-04-21 19:09:03.353603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4793c8072f'
down_revision: Union[str, Sequence[str], None] = '4ce1c87fd363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('partner_type', sa.Enum('CUSTOMER', 'SUPPLIER', 'BOTH', name='business_partner_type', native_enum=False, length=20), server_default='CUSTOMER', nullable=False),
    sa.Column('tax_office', sa.String(length=150), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('authorized_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_partners_name'), 'business_partners', ['name'], unique=True)
    op.create_index(op.f('ix_business_partners_partner_type'), 'business_partners', ['partner_type'], unique=False)
    op.create_index(op.f('ix_business_partners_tax_number'), 'business_partners', ['tax_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_partners_tax_number'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_partner_type'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_name'), table_name='business_partners')
    op.drop_table('business_partners')
    # ### end Alembic commands ###
